services:
  php:
    container_name: aoc-2024-php
    image: php:8.4-cli
    working_dir: /app
    volumes:
      - ./src:/app
      - ./data:/data
    stdin_open: true
    tty: true

  go:
    container_name: aoc-2024-go
    image: golang:1.21
    working_dir: /app
    volumes:
      - ./src:/app
      - ./data:/data
    stdin_open: true
    tty: true
