services:
  php:
    container_name: aoc-2024-php
    image: php:8.4-cli
    working_dir: /app
    volumes:
      - ./php:/app
      - ./data:/data
    stdin_open: true
    tty: true

  go:
    container_name: aoc-2024-go
    image: golang:1.23
    working_dir: /app
    volumes:
      - ./go:/app
      - ./data:/data
    stdin_open: true
    tty: true

  elixir:
    container_name: aoc-2024-elixir
    image: elixir:1.15
    working_dir: /app
    volumes:
      - ./elixir:/app
      - ./data:/data
    stdin_open: true
    tty: true

  python:
    container_name: aoc-2024-python
    image: python:3.12
    working_dir: /app
    volumes:
      - ./python:/app
      - ./data:/data
    stdin_open: true
    tty: true
